<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Mosaik.Core</RootNamespace>
    <AssemblyName>Mosaik.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- ASP.NET Core shared framework — BindNever, ModelBuilder, IServiceCollection için -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>

</Project>
