<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Mosaik.Modules.SOP</RootNamespace>
    <AssemblyName>Mosaik.Modules.SOP</AssemblyName>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
    <PackageReference Include="HtmlSanitizer" Version="9.0.892" />
    <ProjectReference Include="..\Mosaik.Core\Mosaik.Core.csproj" />
  </ItemGroup>

</Project>
