<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Mosaik</RootNamespace>
    <AssemblyName>Mosaik</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mosaik.Core\Mosaik.Core.csproj" />
    <!-- Plan 16.6 modül referansları — yeni vNext modüller burada listelenir -->
    <ProjectReference Include="..\Mosaik.Modules.Tamim\Mosaik.Modules.Tamim.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.18" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.18" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.1" />
  </ItemGroup>

</Project>
